parameters:
- name: artifactoryServiceConnection
  type: string
  default: new
- name: artifactoryPlatformOIDCServiceConnection
  type: string
  default: new1
stages:
- stage: __default
  jobs:
  - job: Job
    steps:
    - task: PowerShell@2
      displayName: Create JFROG_CLI_TEMP_DIR for newer versions of the JFrog CLI (>=1.39.5) as work around for error when it can not find the temp directory.
      inputs:
        targetType: inline
        script: "\nif (!(Test-Path $(jfrog_cli_temp_dir)))\n{\n  if($PSVersionTable.PSVersion.Major -eq '7'){\n    mkdir -p $(jfrog_cli_temp_dir)\n  } else {\n    mkdir -Path $(jfrog_cli_temp_dir)\n  }          \n}\n\nWrite-Host \"$(jfrog_cli_temp_dir) now confirmed to exist\""
    - task: JFrogToolsInstaller@1
      inputs:
        artifactoryConnection: sample-pipeline-service-v2
        cliInstallationRepo: jfrog-cli-v2
        installCustomVersion: true
        cliVersion: 2.77.0
      displayName: Install JFrog CLI v2.77.0
    - task: PowerShell@2
      displayName: Install curl dev tools
      inputs:
        targetType: inline
        script: sudo apt update && sudo apt-get -y install libcurl4-openssl-dev r-base-core
        pwsh: true
    - task: PowerShell@2
      displayName: Allow installation to hosts R library
      inputs:
        targetType: inline
        script: sudo chmod -R 777 /usr/local/lib/R
        pwsh: true
    - task: JfrogCliV2@1
      name: jfStep
      displayName: Obtain OIDC token
      inputs:
        jfrogPlatformConnection: new1
        command: jf rt ping
    - task: PowerShell@2
      displayName: Show OIDC details
      inputs:
        targetType: inline
        script: |
          echo "OIDC Username: $($jfStep.oidc_user)"
          echo "OIDC Token: $env:oidc_token"
        pwsh: true
    - task: PowerShell@2
      displayName: Create CRAN download script
      inputs:
        targetType: inline
        script: |
          $rscript = @'
            #!/usr/bin/env Rscript

            local(
              {
                r <- list("cran-remote" = "http://10.160.0.6:8082/artifactory/cran-remote/")
                options(repos = r)
              }
            )

            install.packages("ps", headers = c("X-JFrog-Art-Api" = "$env:oidc_token"))
            quit(status=0)
          '@

          Set-Content -Path './install_from_cran_remote.r' -Value $rscript
        pwsh: true
    - task: PowerShell@2
      displayName: Install from CRAN remote
      continueOnError: true
      inputs:
        targetType: inline
        script: |
          Write-Output "install ps from cran remote"
          Rscript ./install_from_cran_remote.r
          Write-Output "Installing done"
        pwsh: true
    - task: CmdLine@2
      displayName: Show R site-library
      inputs:
        script: |
          echo /usr/local/lib/R/site-library
          ls -al /usr/local/lib/R/site-library
